apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtf-ingress-template
  namespace: rtf 
  labels:
    business-group: business-group-id
    environment: environment-id
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /\$2
    nginx.ingress.kubernetes.io/ssl-redirect: \"true\"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/app-name(/|$)(.*) /\$2 break; 
spec:
  ingressClassName: rtf-nginx
  rules:
  - host: demo.astellas.com
    http:
      paths: 
      - pathType: ImplementationSpecific
        path: /app-name
        backend: 
          service:
            name: service-name
            port:
              number: 80
---

apiVersion: v1
kind: ConfigMap
data:
  enable-underscores-in-headers: \"true\"
metadata:
  name: nginx-configuration
  namespace: ingress-nginx"