apiVersion: v1
kind: Service
metadata:
  name: my-mule-gke
  labels:
    app: hello
  annotations:
    cloud.google.com/app-protocols: '{"my-mule-gke-tls": "HTTPS"}'
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: my-mule-gke tls
      port: 443
      targetPort: 8443
  
  
